### ISSUE TITLE
Respect `language=` priorities for road names

### ISSUE THREAD

**Issue by zstadler** [ZeLonewolf/openstreetmap-americana#624] opened 2022-12-19 19:57 UTC
It seems like English is receiving higher priority than defined by `language=he,en`

When using [a map with `language=he`](https://zelonewolf.github.io/openstreetmap-americana/#language=he,en&map=19/32.0784103/34.7901903) street names are shown in Hebrew:

![image](https://user-images.githubusercontent.com/1304610/208508383-4e667c02-6323-4a32-9c69-391ab5636af1.png)

However, if English is added as a secondary language,  in [a map with `language=he,en`](https://zelonewolf.github.io/openstreetmap-americana/#language=he,en&map=19/32.0784103/34.7901903), the street names are shown in English rather than Hebrew:

![image](https://user-images.githubusercontent.com/1304610/208508867-9f1e7146-4322-47ef-be14-994ef38102f4.png)

Language priorities seem to work as expected for other map elements, such as country and city names.

**Comment by zekefarwell** [comment] 2022-12-19 20:11
I think this is probably related to #619.  Although OpenMapTiles includes `name:lang` fields for many languages on place names, for road names it still only has fields for German and English.  Probably what is happening here is that with `language=he` set the map is falling back to the default local name field, but with `language=he,en` it is falling back to `name=en` first.

**Comment by 1ec5** [comment] 2022-12-19 21:05
Duplicate of #618.

**Closed by 1ec5** 2022-12-19 21:05 UTC
Labels: openmaptiles
